### ISSUE TITLE
Can't make documented processor function work

### ISSUE THREAD

**Issue by ghost** [elycruz/rollup-plugin-sass#24]
```js
// Rollup plugins.
import babel from 'rollup-plugin-babel';
import cjs from 'rollup-plugin-commonjs';
import globals from 'rollup-plugin-node-globals';
import replace from 'rollup-plugin-replace';
import resolve from 'rollup-plugin-node-resolve';
import sass from 'rollup-plugin-sass';
import postcss from 'rollup-plugin-postcss';

export default {
  dest: 'build/app.js',
  entry: 'src/index.jsx',
  format: 'iife',
  plugins: [
    resolve({
      browser: false,
      main: true
    }),
    sass({
      processor(style, id) {
        return postcss([ require('autoprefixer') ])
          .process(/* css */)
          .then((result) => {
            return result.css;
          });
      },
      output: 'styles.css'      
    }),
    babel({
      babelrc: false,
      exclude: 'node_modules/**',
      presets: [ 'es2015-rollup', 'stage-0', 'react' ],
      plugins: [ 'external-helpers' ]
    }),
    cjs({
      exclude: 'node_modules/process-es6/**',
      include: [
        'node_modules/deep-equal/**',
        'node_modules/fbjs/**',
        'node_modules/invariant/**',
        'node_modules/history/**',
        'node_modules/hoist-non-react-statics/**',
        'node_modules/lodash/**',
        'node_modules/object-assign/**',
        'node_modules/query-string/**',
        'node_modules/react/**',
        'node_modules/react-dom/**',
        'node_modules/react-redux/**',
        'node_modules/react-router/**',
        'node_modules/redux/**',
        'node_modules/strict-uri-encode/**',
        'node_modules/warning/**'
      ]
    }),
    globals(),
    replace({ 'process.env.NODE_ENV': JSON.stringify('development') })
  ],
  sourceMap: true
};
```

Error log:

```
Error transforming /Users/user/git/babel-react-rollup-starter/src/sass/index.scss with 'sass' plugin: postcss(...).process is not a function
TypeError: Error transforming /Users/user/git/babel-react-rollup-starter/src/sass/index.scss with 'sass' plugin: postcss(...).process is not a function
    at Object.processor (/Users/user/git/babel-react-rollup-starter/config/dev.js:26:12)
    at Object._callee$ (/Users/user/git/babel-react-rollup-starter/node_modules/rollup-plugin-sass/dist/rollup-plugin-sass.js:103:32)
    at tryCatch (/Users/user/git/babel-react-rollup-starter/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/user/git/babel-react-rollup-starter/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/user/git/babel-react-rollup-starter/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/user/git/babel-react-rollup-starter/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/user/git/babel-react-rollup-starter/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/user/git/babel-react-rollup-starter/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at /Users/user/git/babel-react-rollup-starter/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at Object.transform (/Users/user/git/babel-react-rollup-starter/node_modules/rollup-plugin-sass/dist/rollup-plugin-sass.js:144:10)
```

**Comment by ghost** [comment]
Tried the same thing using `import postcss from 'postcss'`, but that didn't work either.

**Comment by brendan-jefferis** [comment]
Following on from that, I changed the name of the parameter `style` to `css` which fixed the above error but then got:

```
postcss(...).process is not a function
```

I'm new to postcss but I'm pretty sure it has a process function..? Full rollup config below

```
import sass from "rollup-plugin-sass";
import postcss from "rollup-plugin-postcss";

export default {
    entry: "src/app.js",
    format: "cjs",
    dest: "dist/app.js",
    format: "iife",
    sourceMap: true,
    plugins: [
        sass({
            output: "dist/app.css",
            processor(css) {
                return postcss([ require("autoprefixer") ])
                    .process(css)
                    .then(result => result.css)
                }
            })
    ]
}
```

**Comment by nathancahill** [comment]
Posted on SO, but posting here for future. Here is my working config:

```js
import sass from 'rollup-plugin-sass'
import autoprefixer from 'autoprefixer'
import postcss from 'postcss'

sass({
    processor: css => postcss([autoprefixer])
        .process(css)
        .then(result => result.css)
})
```

**Comment by ghost** [comment]
@nathancahill got it right. Now the readme just needs updating.
