### ISSUE TITLE
Does this plugin support @import in SASS files?

### ISSUE THREAD

**Issue by Reinmar** [elycruz/rollup-plugin-sass#25]
I've got a simple SASS file `theme.scss`:

```sass
@import 'sth.scss';
```

And Rollup config:

```js
const path = require( 'path' );
const nodeResolve = require( 'rollup-plugin-node-resolve' );
const sassRollupPlugin = require( 'rollup-plugin-sass' );

export default {
	entry: './entry-point.js',
	format: 'iife',

	dest: path.join( 'build', 'dist', 'ckeditor.js' ),

	plugins: [
		nodeResolve(),

		sassRollupPlugin( {
			insert: true
		} )
	]
};
```

And I get this:

```
Error parsing /www/ckeditor5/ckeditor5/node_modules/ckeditor5-editor-classic/theme/theme.scss: Unexpected character '@' (1:0) in /www/ckeditor5/ckeditor5/node_modules/ckeditor5-editor-classic/theme/theme.scss
```

I thought that SCSS imports would be handled by node-sass itself, so this error is surprising. But then, I don't see any tests for your package which would check imports. So is it a missing feature of this plugin or should I use it with some other package like https://www.npmjs.com/package/node-sass-import?

**Comment by Reinmar** [comment]
Turns out that the initial issue was in a totally different place. This specific file was filtered out by https://github.com/differui/rollup-plugin-sass/blob/58dc13223ad5097fe8a630a19cfab2fa036af4b8/src/index.js#L35 because it's localted in `node_modules`.

So I configured this plugin to not exclude any files:

```js
		sassRollupPlugin( {
			insert: true,
			include: '**/*.scss',
			exclude: []
		} )
```

Now the error is more reasonable:

```
Error transforming /www/ckeditor5/ckeditor5/node_modules/ckeditor5-editor-classic/theme/theme.scss with 'sass' plugin: File to import not found or unreadable: ~ckeditor5-theme-lark/theme/theme.scss.
Parent style sheet: stdin
Error: Error transforming /www/ckeditor5/ckeditor5/node_modules/ckeditor5-editor-classic/theme/theme.scss with 'sass' plugin: File to import not found or unreadable: ~ckeditor5-theme-lark/theme/theme.scss.
Parent style sheet: stdin
    at Object.module.exports.renderSync (/www/ckeditor5/ckeditor5/node_modules/node-sass/lib/index.js:434:16)
    at Object._callee$ (/www/ckeditor5/ckeditor5/node_modules/rollup-plugin-sass/dist/rollup-plugin-sass.js:89:32)
    at tryCatch (/www/ckeditor5/ckeditor5/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/www/ckeditor5/ckeditor5/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:337:22)
```

Still, I need to find out how to use a Node-like resolution algorithm. I managed to compile the same SASS files with Webpack and hopefully I'll be able to do the same with Rollup.

**Comment by Reinmar** [comment]
OK, if anyone's interested, this was enough in my case:

```js
sassRollupPlugin( {
	insert: true,
	include: '**/*.scss',
	exclude: [],
	options: {
		importer( url /*, prev */ ) {
			// E.g. @import '~ckeditor5-theme-lark/theme/theme.scss';
			// See https://github.com/jtangelder/sass-loader#imports
			if ( url.startsWith( '~' ) ) {
				const path = process.cwd() + '/node_modules/' + url.slice( 1 );

				return {
					file: path
				};
			}
		}
	}
} )
```

However, it only worked because I've got all dependencies straight in `CWD/node_modules/`. If that wouldn't be true, then a full Node resolution algorithm would be needed.

**Comment by nathancahill** [comment]
You can add node_modules to your SASS include path like this:

```js
sass({
    options: {
        includePaths: ['node_modules']
    }
})
```

**Comment by Alfredo-Delgado** [comment]
I ended up having to split the difference between @Reinmar and @nathancahill:

```js
const vueOptions = {
  scss: {
    includePaths: [ 'node_modules/' ],
    importer(path) {
      return { file: path[0] !== '~' ? path : path.slice(1) };
    }
  }
};
```

**Comment by chrismpettyjohn** [comment]
I recently encountered this when working on a Mono Repo using Yarn Workspaces.  My problem was a combination of `~` not being resolved properly @Reinmar and my node_modules being hosted a few directories back from the cwd.  I ended up with the following, however your milage may vary based on your specific structure

```javascript
 scss({
      output: './dist/themes.css',
      failOnError: true,
      includePaths: ['node_modules/'],
      importer(url /*, prev */) {
        // E.g. @import '~ckeditor5-theme-lark/theme/theme.scss';
        // See https://github.com/jtangelder/sass-loader#imports
        if (url.startsWith('~')) {
          const filePath = path.resolve(
            '..',
            '..',
            '..',
            '..',
            'node_modules',
            url.slice(1)
          );

          return {
            file: filePath,
          };
        }
      },
    }),
```
