### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by sam-s4s** [elycruz/rollup-plugin-sass#8]
Just from importing the plugin in my rollup.config.js, even when I'm not calling sass(), I get this error:

```
Cannot find module 'babel-runtime/regenerator'
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\web\node_modules\rollup-plugin-sass\dist\rollup-plugin-sass.cjs.js:5:43)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions..js (C:\web\node_modules\rollup\bin\rollup:763:6)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by differui** [comment]
Cause **babel-plugin-transform-runtime** was not installed(#5).New version [0.2.2](https://www.npmjs.com/package/rollup-plugin-sass) was published.
