### ISSUE TITLE
Bug in version 1.2.5

### ISSUE THREAD

**Issue by diego-antonelli** [elycruz/rollup-plugin-sass#81]
I am constantly receiving this error after upgrade the plugin version to 1.2.5. Downgrading to 1.2.4 works fine..

``` 
 [!] TypeError: The "path" argument must be of type string. Received an instance of RegExp
 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of RegExp
     at validateString (internal/validators.js:124:11)
     at Object.resolve (path.js:1074:7)
     at /tmp/pwt_test_1711/node_modules/rollup-plugin-sass/node_modules/rollup-pluginutils/dist/pluginutils.cjs.js:183:68
     at Array.map (<anonymous>)
     at Object.createFilter (/tmp/pwt_test_1711/node_modules/rollup-plugin-sass/node_modules/rollup-pluginutils/dist/pluginutils.cjs.js:183:35)
     at Object.plugin [as default] (/tmp/pwt_test_1711/node_modules/rollup-plugin-sass/src/index.ts:134:14)
```

**Comment by elycruz** [comment]
Hey @diego-antonelli rollup-pluginutils re-removed and replaced with @rollup/pluginutils@3.1 .
Merged pull request: #82
